import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
  keywords: 'next, react, app, users',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          href='https://bootswatch.com/5/flatly/bootstrap.min.css'
        />
      </head>
      <body>
        <Navbar />
        <div className='container'>{children}</div>
      </body>
    </html>
  );
}
